name: Daily Instagram Video Uploader

on:
  schedule:
    # Runs at 6:00 PM IST every day (12:30 UTC)
    # CRON format: minute hour day_of_month month day_of_week
    - cron: '30 12 * * *' # This cron job runs at 12:30 UTC, which is 6:00 PM IST
  
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI

jobs:
  upload-video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # cloudinary and requests needed for script, subprocess is built-in
        pip install cloudinary requests 

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # GOOGLE_CLIENT_SECRETS अब आवश्यक नहीं है क्योंकि हम सीधे Instagram एक्सेस टोकन का उपयोग कर रहे हैं।
    # इसलिए, client_secret.json बनाने वाला स्टेप यहाँ हटा दिया गया है।

    - name: Run Instagram Uploader Script
      env:
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }} # आपका Instagram लॉन्ग-लिव्ड एक्सेस टोकन
        INSTAGRAM_BUSINESS_ACCOUNT_ID: ${{ secrets.INSTAGRAM_BUSINESS_ACCOUNT_ID }} # आपका Instagram Business Account ID
      run: |
        python instagram_uploader.py
